# Generated by Django 4.0.5 on 2023-01-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EEDC',
            new_name='Customer',
        ),
    ]
