# Generated by Django 4.0.5 on 2023-01-02 03:21

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_eedc_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='c_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
