# Generated by Django 4.0.5 on 2023-01-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment_customer_c_phone_alter_customer_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commen', to='accounts.customer'),
        ),
    ]
