# Generated by Django 4.0.5 on 2023-01-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AddField(
            model_name='payment',
            name='custo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='custo', to='accounts.customer'),
        ),
    ]
