# Generated by Django 4.0.5 on 2023-01-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_payment_customer_payment_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='custo',
        ),
        migrations.AddField(
            model_name='payment',
            name='c_phone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
